import type { Metadata } from "next";
import '@fontsource/quicksand';
import Header from '../../components/Header.jsx'
import Searcher from '../../components/Searcher.jsx'
import Footer from '../../components/Footer.jsx'
import "./globals.css";

export const metadata: Metadata = {
  title: "SVGPRO app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <Header className=""/>
        
        <main className="flex-1">
          {children}
        </main>
      </body>
    </html>
  );
}
